version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "2000:2000"
