version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3080:80"
    environment:
      - VITE_REACT_APP_API_URL=${VITE_REACT_APP_API_URL}
    depends_on:
      - server

  server:
    build:
      context: ./server
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}