version: '3.8'

services:
  client:
    build:
      context: ./opnvaarta
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./opnvaarta-server
    ports:
      - "5000:5000"
